### ISSUE TITLE
[SOLVED] Did not get the result

### ISSUE THREAD

**Issue by mnavaidd** [alexmanni/InterFaceGAN_StyleGAN#1]
I have run the same notebook in `google colab` but did not get the same result as you mentioned.

**Comment by alexmanni** [comment]
Hi, I forgot to delete an old .npy file from a previous run, try it now: https://colab.research.google.com/drive/1ik8wpap09kJxOzG4Kn2G3f4cNlryYxAL?usp=sharing

**Comment by mnavaidd** [comment]
Thanks, Will check and update you

**Comment by mnavaidd** [comment]
Thanks, now its working.
Is that possible to give `rafael nadal` images as input and generate `rafael nadal` with `aging `?

**Comment by alexmanni** [comment]
Sure, run the last cell of the notebook, this will delete the sample image of Di Caprio and related files generated. Put your image of rafael nadal (must be in high resolution to obtain good result)  in this folder: **_StyleGAN/stylegan-encoder/input_** then run cells starting from **ALIGNMENT** section

**Comment by alexmanni** [comment]
SOLVED

**Comment by mnavaidd** [comment]
Thanks, its fixed now, thanks for your help
